### ISSUE TITLE
Work with Releases ?

### ISSUE THREAD

**Issue by ultrajericho** [JaydenMaalouf/azure-pipelines-terraform-output#1]
Hello,

Does this plugin works with Azure Releases ? Or is it only for Azure Pipelines YAML ?

Regards,

**Comment by JaydenMaalouf** [comment]
Currently, this plugin doesn't support release pages. 

I can take a look at the feasibility of adding support for this in a few days

**Comment by JaydenMaalouf** [comment]
> Hello,
> 
> Does this plugin works with Azure Releases ? Or is it only for Azure Pipelines YAML ?
> 
> Regards,

Good news!
I have successfully added support for Release deployments to the plugin
![image](https://user-images.githubusercontent.com/7008565/223703686-12afca63-6951-464e-bfe1-f22f886c0653.png)
Each stage should have it's own attachments, so you won't get cross contamination when viewing the plans

This is currently live on the Azure DevOps Marketplace!

**Comment by ultrajericho** [comment]
Ok @JaydenMaalouf thank you for your reactivity, I will test this!

**Comment by ultrajericho** [comment]
@JaydenMaalouf I'm not sure it is resolved as my Terraform Plan tab is still empty when I do a Terraform Plan.  How did you passed your "test" Plan to this tab ?

![image](https://user-images.githubusercontent.com/74764876/224070153-08705a41-add3-4563-bbf8-2d94b9607f42.png)
