### ISSUE TITLE
Terraform Plan Tab Scrollbars

### ISSUE THREAD

**Issue by brad2190** [JaydenMaalouf/azure-pipelines-terraform-output#10]
Terraform Plan Tab in Run Summary

In Microsoft Edge 114.0.1823.90 where a Terraform Plan is produced which has information lines wider than the tab frame this information is not visible.

Is it possible to enable horizontal scroll bars for this tab?

**Comment by JaydenMaalouf** [comment]
Hey,
I have just released a new version that adds some overflow to allow scrollbars to show when the plan exceeds the width of the window
Let me know if it works as expected

See the changes here #11

**Comment by JaydenMaalouf** [comment]
Going to assume this one is all good. Closing this off

**Comment by brad2190** [comment]
Apologies for delay I was away. I can confirm it's working as expected now
