### ISSUE TITLE
Node Version End-of-Life

### ISSUE THREAD

**Issue by Red1971** [JaydenMaalouf/azure-pipelines-terraform-output#14]
Good day. I have started to receive a warning on the Node version being end-of-life. Is this something you update? (I use this task in all my pipelines and it is brilliant).

The actual warning message i get is shown below….

##[warning]Task 'Terraform Load Output' version 1 (TerraformOutput@1) is dependent on a Node version (10) that is end-of-life.

Contact the extension owner for an updated version of the task. Task maintainers should review Node upgrade guidance: https://aka.ms/node-runner-guidance

**Comment by fardarter** [comment]
Here for the same reason.

**Comment by yirmio** [comment]
Same here...

**Comment by seanezell** [comment]
Ditto!

It's not just this task, we are also getting this with AWS Toolkit for Azure DevOps and the Terraform extension.

**Comment by JaydenMaalouf** [comment]
This has been resolved in version 1.2.2 of the plugin - please visit your Azure DevOps extension page to update

**Comment by fardarter** [comment]
@JaydenMaalouf Thank you!
