### ISSUE TITLE
TF Plan not displayed in Release 

### ISSUE THREAD

**Issue by ultrajericho** [JaydenMaalouf/azure-pipelines-terraform-output#3]
Hello @JaydenMaalouf,

Sorry to bother you, I don't know if you follow the closed issues so I create another one here.

I installed your extension and now I can see the "Terraform Plan" tab in the Release stages... BUT it stays empty even with a Terraform plan executed and an output generated...

![image](https://user-images.githubusercontent.com/74764876/224138003-3a96c4d9-eff4-4be7-9edd-abf5a1d7765f.png)

Can you tell me if I do something wrong or if it is an issue ?

Regards,

**Comment by JaydenMaalouf** [comment]
> Hello @JaydenMaalouf,
> 
> 
> 
> Sorry to bother you, I don't know if you follow the closed issues so I create another one here.
> 
> 
> 
> I installed your extension and now I can see the "Terraform Plan" tab in the Release stages... BUT it stays empty even with a Terraform plan executed and an output generated...
> 
> 
> 
> ![image](https://user-images.githubusercontent.com/74764876/224138003-3a96c4d9-eff4-4be7-9edd-abf5a1d7765f.png)
> 
> 
> 
> Can you tell me if I do something wrong or if it is an issue ?
> 
> 
> 
> Regards,
> 
> 

Have you ensured that you have called the TerraformOutput task?

This is required to run before the outputs show up

**Comment by ultrajericho** [comment]
Sorry @JaydenMaalouf , my input was incorrect. Now it works perfectly ! 

Thanks a lot!

**Comment by ultrajericho** [comment]
Ok no... 
I don't understand why but it's empty again :/ 
This is strange because the logs are showing it was uploaded... 
![image](https://user-images.githubusercontent.com/74764876/224188389-6705b45d-d455-4320-afd8-d24967f6601a.png)

I can't understand why it worked one time.


@JaydenMaalouf , is it possible that the "Terraform Plan" tab is cleaned when the stage ends ... or when another jobs starts after the one containing your task?

**Comment by ultrajericho** [comment]
Ok it looks like the tab is cleaned when the job ends.

I manage to see the tab populated like that before the job ends : 
![image](https://user-images.githubusercontent.com/74764876/224189303-950094cf-60f0-4d35-b3e1-bba46fbea569.png)

But when the stage is complete : 
![image](https://user-images.githubusercontent.com/74764876/224189385-f8b83aea-9bd2-4482-9da9-a47aae5dc1f7.png)

**Comment by JaydenMaalouf** [comment]
> Ok it looks like the tab is cleaned when the job ends.
> 
> I manage to see the tab populated like that before the job ends : ![image](https://user-images.githubusercontent.com/74764876/224189303-950094cf-60f0-4d35-b3e1-bba46fbea569.png)
> 
> But when the stage is complete : ![image](https://user-images.githubusercontent.com/74764876/224189385-f8b83aea-9bd2-4482-9da9-a47aae5dc1f7.png)

I cannot replicate this behaviour. I tested within 2 organisations and with self-hosted and Microsoft Hosted Agents.
I have found an issue where if you have slow internet, the drop down list may not populate on first click - however, it seems to load fine after attempting to reopen the drop down.
I will attempt to fix that issue in an upcoming release.

**Comment by ultrajericho** [comment]
> > Ok it looks like the tab is cleaned when the job ends.
> > I manage to see the tab populated like that before the job ends : ![image](https://user-images.githubusercontent.com/74764876/224189303-950094cf-60f0-4d35-b3e1-bba46fbea569.png)
> > But when the stage is complete : ![image](https://user-images.githubusercontent.com/74764876/224189385-f8b83aea-9bd2-4482-9da9-a47aae5dc1f7.png)
> 
> I cannot replicate this behaviour. I tested within 2 organisations and with self-hosted and Microsoft Hosted Agents. I have found an issue where if you have slow internet, the drop down list may not populate on first click - however, it seems to load fine after attempting to reopen the drop down. I will attempt to fix that issue in an upcoming release.

Honestly I have this in 100% of my tests.
I use Self Hosted agents. But it is not a slow internet issue at all, it is impossible and I have the same results from differents places and PCs.

And as I said, the terraform Plan tab/the drop down list is populated until the job ends. After it ends, it is empty.

See on the screenshot below, the Terraform Plan tab is populated if I check it during the execution of the 2 tasks I have pointed out in red. After, when the job is finished, the tab become empty : 
![image](https://user-images.githubusercontent.com/74764876/225118030-8313970f-7649-4084-84a2-d3d59799c0d6.png)

**Comment by ultrajericho** [comment]
@JaydenMaalouf  Sorry to bother you again, but do you have any recommendation or workaround to do on my side to make this work ?

**Comment by JaydenMaalouf** [comment]
> @JaydenMaalouf Sorry to bother you again, but do you have any recommendation or workaround to do on my side to make this work ?

Apologies for the delay. I've made a change to the plugin to load the attachments before attempting to render the dropdown. Can you see if this helps?

If not, please open the Developer console. There should be some debug logs in the console, if you can screenshot those and send them here, that would be great!

There should also be a network request, it should look like this:
![image](https://user-images.githubusercontent.com/7008565/226574954-bdefa3c8-bb70-4510-8850-ee29af5aeb97.png)
Please send me the response to this request
The attachments themselves are locked to your organization but please obfuscate as necessary

**Comment by ultrajericho** [comment]
Hello @JaydenMaalouf ,

Thanks for your answer. No worries for the delay, it's already nice to answer me.

Apparently the fix is not working either, but now instead of nothing in the dropdown : I see a "Loading" message 
![image](https://user-images.githubusercontent.com/74764876/226662155-bd28e9da-17b4-420d-82c8-fefdf12edead.png)

In fact, in the Network window, I get a 404 error :( 
![image](https://user-images.githubusercontent.com/74764876/226661419-158f892e-f0c6-4b7d-b3cd-8fd1adb278ee.png)

Something weird is that I have 4 "terraform.plan" calls everytime I click on the "Terraform Plan" tab. And there is always one that works :
![image](https://user-images.githubusercontent.com/74764876/226663300-25b96ba5-fc86-4f48-911d-e20ae4c22998.png)
... but nothing appears in the dropdown.


Again, I really think it can be because I have 4 jobs, and 3 of them can be skipped. Maybe it does 4 calls because I have 4 jobs... 1 works because it really produced a plan the 3 others are failling because they are Skipped/Empty jobs.
Is it something that sounds realistic... and fixable for you ?
![image](https://user-images.githubusercontent.com/74764876/226665076-ee51ab0a-6255-480b-958d-e167fd23d833.png)

**Comment by JaydenMaalouf** [comment]
> Hello @JaydenMaalouf ,
> 
> Thanks for your answer. No worries for the delay, it's already nice to answer me.
> 
> Apparently the fix is not working either, but now instead of nothing in the dropdown : I see a "Loading" message ![image](https://user-images.githubusercontent.com/74764876/226662155-bd28e9da-17b4-420d-82c8-fefdf12edead.png)
> 
> In fact, in the Network window, I get a 404 error :( ![image](https://user-images.githubusercontent.com/74764876/226661419-158f892e-f0c6-4b7d-b3cd-8fd1adb278ee.png)
> 
> Something weird is that I have 4 "terraform.plan" calls everytime I click on the "Terraform Plan" tab. And there is always one that works : ![image](https://user-images.githubusercontent.com/74764876/226663300-25b96ba5-fc86-4f48-911d-e20ae4c22998.png) ... but nothing appears in the dropdown.
> 
> Again, I really think it can be because I have 4 jobs, and 3 of them can be skipped. Maybe it does 4 calls because I have 4 jobs... 1 works because it really produced a plan the 3 others are failling because they are Skipped/Empty jobs. Is it something that sounds realistic... and fixable for you ? ![image](https://user-images.githubusercontent.com/74764876/226665076-ee51ab0a-6255-480b-958d-e167fd23d833.png)

Hello again,
I was successfully able to replicate the issue last night based on your comments. Thanks for being so patient!
I have just pushed up my changes. The results should now successfully load even when a task was skipped or failed.

Please test it out and let me know if it is working as expected!
You may need to force an update on the plugin by navigating to the extensions page in your organisation (it should automatically pull the latest)
ie. https://dev.azure.com/ORG_HERE/_settings/extensions?tab=installed&extension=JaydenMaalouf.terraform-output

**Comment by ultrajericho** [comment]
Hello @JaydenMaalouf ,
Thanks for your quick answer again, now it seems to work ! Even with my old releases.

 Thanks a lot for your help and your reactivity !
 
 Regards,
